---
title: "Karim Ladak: Curriculum Vitae"
author:  "[karim.ladak@gmail.com](mailto:karim.ladak@gmail.com)"
output:
  html_document:
    fig_width: 1
---

----

## Summary

My academic and professional experience focuses on the development and implementation of information technology solutions to solve complex business problems, particularly those involving data, its interpretation and associated quantitative analytics.  In particular, I have significant experience in mathematical model development and statistical analysis, with concomitant experience in business case development, project planning and management, technical design and software development of Business Intelligence, Data Warehousing and Mathematical/Statistical efforts, and have led or participated in teams that provided the foregoing solutions.

I have considerable experience in leading highly technical projects and teams. I have served as a Project Manager for several major quantitative projects with peak staff loading of over 15 staff and multi-million dollar budgets, and have led multidisciplinary teams that have developed various mathematical and statistical solutions for clients in the financial industry, power generation industry and in regulatory sectors. 

My recent technical experience includes the following: \textit{Statistical Data Analysis} (exploratory data analysis, multivariate analysis, and sampling plan development); \textit{Mathematical Algorithm Development} (securities market fraud detection, yield management algorithms, energy markets surveillance, manufacturing quality control); \textit{Software Coding and Development} (Visual Studio, Python, SQL, PHP, C/C++, VBA, Javascript, R Statistical System and RStudio); \textit{Report Writing} (expert witness reports, strategic analysis reports, requirements specifications, software design documents, coding standards); \textit{Project Management} (utilizing project management methodologies to manage multidisciplinary teams of over 15 staff and budgets of over \$5 million); as well as Proposal Development and Presentation, and Contract Negotiation.

----

## Education

- University of British Columbia, Vancouver, BC
    - B.SC. IN PHYSICAL GEOGRAPHY (GEOMORPHOLOGY)
    - Focus on Fluvial Geomorphology
    
- University of British Columbia, Vancouver, BC
    - B.SC. IN COMPUTER SCIENCE
    - Focus on Software Development (as opposed to Hardware Design)

- University of British Columbia, Vancouver, BC
    - M.SC. IN STATISTICS
    - Dissertation: Resampling-based Variance Estimators

----

## Skills

- Programming: Visual Studio, Python, SQL, PHP, C/C++, VBA, Javascript, LaTeX
- Data Science: R Statistical System, RStudio, Knitr, D3.JS
- Statistics: Exploratory data analysis, multivariate analysis, sampling plan development, regression analysis, ANOVA
- Algorithms: Securities market fraud detection, yield & revenue management, energy markets surveillance, financial valuation
- Writing: Strategic analysis reports, requirements specifications, software design documents, coding standards

----

## Work Experience

- KL Consulting Inc, Brampton, ON 
    - MANAGEMENT CONSULTANT: 2004 - PRESENT
    - Provision of Management Consulting services to clients across many industries, including financial services, financial asset securiti-sation, investment management, and law enforcement.
    - Utilization of a variety of data science skillsets, ranging from web technologies to data science tools.
    - Experienced with technical design, software development, mathematical modeling and statistical analysis.
    
- IBM Global Services, Toronto, ON
    - ASSOCIATE PARTNER: 2002 - 2004
    - Moved to IBM as part of sale of PwC Consulting practice.
    - Primarily focused on a single electricity generation client.
    - Part of Data Warehousing practice.
    
- PwC PricewaterhouseCoopers, Vancouver, BC and Toronto, ON
    - ASSOCIATE PARTNER: 1990 - 2002
    - First employment post-University.
    - Worked within many different units, including Audit and Assurance, Small Business Services, and Management Consulting.
    - Served clients from the following industries: Airlines, Banking, Financial Services, Forestry, Government, and Hospitality, StockExchanges
 
----

## Project Experience

#### Project Management Assignments

For a leading, diversified North American energy generation company, simultaneously served as Program Manager and Project Manager for three critical projects, with a combined annual budget of over \$3 million dollars, primarily focused on enabling the client to better collect, store and interpret various data sources so as to increase revenues, reduce costs and detect fraudulent or inappropriate behavior by energy traders.  I served as my employers’ primary on-site representative at this client, where these were the employers’ first projects at this major client.  My Project Management responsibilities included the following duties: 

1. Prepare and submit to client for approval, the Project Charter, Budget, and initial Project Workplan.
1. Chair meetings of the project’s Steering Committee, IT Sponsor Committee, and User Committee.
    - Prepare and deliver the project kick-off meeting/presentation.
    - Prepare and deliver progress reports to numerous senior executives who were monitoring these projects.
    - Competently manage staff, monitor and control costs, and handle day-to-day issues to ensure effective daily operations.
    - Perform those iterative processes (i.e. milestone and status reviews) that continually measure the current position and future direction of the project against the project workplan.  
    - Perform project tracking to ensure that the project objectives, defined in the Project Charter, are achieved.
    - Ensure adequate formal project communication of planned and actual effort, trends, accomplishments, resource utilization, issues, changes, and other pertinent indicators. 
1. Achievements as Project Manager:  
    - All three projects delivered more than was initially planned, yet were delivered under-budget.
    - Negotiated a fair and equitable contract between two major organizations (client and my employer). 
    - Clients’ satisfaction with projects led to employer being retained as a ‘go-to-first’ external professional service provider.  

For a major professional investment management organization, served as Project Manager and Subject Matter Expert (“SME”) for the development of a data warehouse to retain global yet granular financial markets data, and investment holdings data with the goal of providing daily holdings, risk, return, and compliance reports.  The implemented solution was a SQL Server database management system with numerous daily feeds from external organizations which provided market, holdings and risk data.  

I served as Project Manager and Statistical SME for the development of a market surveillance data warehouse and integrated analytic system for an electricity exchange, including responsibility for a multi-million dollar budget and a multidisciplinary team of approximately 15 consulting and client staff.  The implemented solution required the design and construction of an Oracle-based Data Warehouse comprising data from eleven Oracle and SQL Server source systems, along with Visual Studio and J2EE-based analysis component.  The project experienced a peak loading of 15 professional staff from my employer, the client and private contractors. The project staff represented an academically and professional diverse group, and included individuals with educational qualifications ranging from PhD’s to BSc’s, with as well as members of the engineering, IT development, electricity generation, and mathematical statistics professions. The project solution has been employed, to date, to surveil electricity trading with market worth of \$48 billion at wholesale prices.  

#### Computational Assignments

For a North American stock exchange, I designed and developed a PC-based computer program that implements a statistical technique for filtering a large dataset and identifying securities with a high probability of manipulation.  This client server computer program was developed using Microsoft Visual Studio, and accessed a server-based non-Microsoft database.   

For a major Canadian bank, developed requirements specifications for customization to fixed income valuation software. 
Served as Project Manager and lead author of a multi-disciplinary team's response to a client Request for Proposals for the installation and implementation of an ERP-based program and funding management system based upon the installation of a PeopleSoft 8-based suite of data warehouse, analysis and financial management software packages.  Our detailed proposal envisioned an 18-month, \$10 million dollar engagement that comprised peak loading of 30 professional staff.   

For an international airline, managed the development of software to simulate, evaluate and identify flaws in the performance of the airline’s passenger forecasting systems.  The result was a complex five thousand line C software program that automated the monitoring of the passenger forecasting system.  

For an international airline, I reviewed the mathematical components of their software that implemented their yield management systems.  This software was written in Borland's Turbo-Pascal.  I identified several significant mathematical errors and computational inefficiencies in this commercial code licensed by over 20 major airlines.  

For a provincial ministry, I designed and developed a PC-based computer program to assess production volumes and to collect related taxes.  This software is now used by both government and industry, to plan and approve this resource-based industry’s production and has been employed in the allocation and collection of annual tax revenues of approximately \$5 billion.  This software was written in Microsoft Visual Studio and used several third party software tools. 

For a provincial ministry, I reviewed mainframe software that calculates and produces invoices for production taxes. This software, written in mainframe Cobol, had been in use since the 1970's.  In addition to identifying several errors and providing detailed suggestions for corrections, I also prepared the specification requirements document to instruct their systems analysts and programmers to code and test new mathematical techniques for implementation into this mainframe system. 

I have also provided software development support to academic researchers in several areas or academic research, ranging from designs of new lotteries to ratings of Grandmaster chess players, from clinical medical trials at a major civic hospital to analysis of drug efficacy for hypertensive patients.  

#### Analytical Assignments

For several North American stock exchanges, I developed automated statistical methods to analyze several gigabytes of live and historical trading information, so as to identify trades and stock listings that are likely being manipulated.  These methods are currently used at two North American stock exchanges to monitor trading with annual turnover of over \$750 billion dollars.  

For a major Canadian bank, I developed mathematical formulas to value investment of money market mutual funds.  I identified errors in previous valuation formulae and developed new and more precise valuation methods and formulae.  These methods are presently used by this client to value mutual and proprietary funds worth an aggregate of over \$500 million dollars. 

For a major financial institution, I derived mathematical methods and developed software to value over \$12 billion in money market instruments.  I identified shortcomings in valuation methods, resulting in a \$20 million increase in valuation of the portfolio.

For a national law enforcement agency, I led a small team comprised of specialists that developed a statistical technique for quantifying the prevalence of economic crime within a nation state and various regional divisions within the country.  Presented the results of our research at various Governmental and industry stakeholder meetings with the goal of ensuring agreement of stakeholders regarding the developed technique, and presented the research results at an international economic crime conference. 

For an international airline, I conducted research into improving the performance of their yield management systems (which are the mathematical algorithms that determine the fare to charge a customer.)  I developed algorithms for automatically selecting homogeneous data subset from larger, relatively heterogeneous data so as to improve forecasting accuracy, in turn leading to increased revenues.

For a major forest company, I provided expert witness testimony before an appeals board, regarding statistical data analysis performed by a provincial ministry.  

For a provincial ministry, I developed a statistical method that selects optimal sampling plans for use in revenue collection from the resource industry. This academically rigorous assignment involved the development of non-parametric, resampling-based variance estimators.  I chaired meetings with ministry and industry officials to develop a new data submission process; designed experiments to determine optimal statistical techniques; created algorithms to automate these functions; and, researched and developed new statistical methods to increase the efficiency and improve the quality of decisions made by ministry staff. These methods have been incorporated into provincial regulations, and are now required, by law, to be used by resource companies.  

For an industry association, I developed statistical sequential sampling-based methods to monitor, on a bimonthly basis, manufacturing defects in approximately 50 product lines with the intent of ensuring that annual production quality meets minimum standards.  These techniques are used to monitor the quality of products worth over \$500 million annually.

For a major federal law enforcement agency, I analyzed stock market activity to determine the presence of stock market manipulation, and assisted in prosecution of such activity by producing reports for submission into court and by providing expert witness testimony.

For a major forest company, I performed detailed statistical analysis of prescribed forest fires (which are purposely initiated, and controlled, forest fires of harvested areas.)  I analyzed over 25,000 data points, representing almost 550 forest fires, and developed a statistical prediction model to estimate the silviculture impact of these fires.  This model is currently in use, helping the company to make decisions about the necessity and impact of prescribed fires.

For a major forest company, I performed a detailed statistical analysis of the shortcomings of a provincial sampling system.  Identified an alternate sampling system that reduced significantly the costs of sampling.

#### Statistical Forecasting and Survey Assignments

I have produced forecasts for clients in transportation, manufacturing and other industries using a variety of statistical techniques, including multiple linear regression and ARIMA time series models.  In particular, I have produced forecasts of the following:

1. Vehicle and passenger traffic for a major ferry corporation;
1. Passenger traffic forecasts, by route and fare class, for a major international airline;
1. Revenue forecasts for a major North American transit system, provincial hydro utility, and other major corporations;
1. Pulp price forecasts for numerous pulp mill holding companies and operators.
1. Loss of income forecasts for submission into court as expert witness reports.

I have provided statistical and mathematical support in several legal cases before provincial Supreme Courts.  This entailed detailed statistical analysis of historical data, forecasts of revenue, and various forms of sensitivity analysis, as well as preparation of legally defensible reports for submission into court. I have assisted in the design and execution of numerous survey and census engagements.  My clients have ranged from provincial government ministries to non-profit organizations to some of world’s largest investment banks. In addition, I have performed general data analysis on numerous data sets, using statistical techniques such as exploratory data analysis, linear model building, analysis of variance, sampling design, design of sampling estimators, and applications of non-parametric estimators.

----

## Service

2008+ Board Member and past Vice Chair, Brampton Public Library, Brampton, ON

2010+ Member and past Chair,Turner Fenton Secondary School Parent Council, Brampton, ON

1990+ Judge,Various Regional and National Science Fairs

----

[Karim Ladak CV](karimladak.github.io/Karim_CV.pdf)

----

----

----

----


## Older 

It's possible to create well-designed websites for free using [RStudio's R Markdown](http://rmarkdown.rstudio.com/) and hosting them on [Github](http://github.com). This is very new and incredibly cool. It is a really powerful way to communicate science using the same reproducible workflow you use for your analyses and collaborations.

***Creating websites with R Markdown can be done without knowing R or HTML, CSS, etc,*** and that's where we'll start. However, R Markdown integrates with these tools so the more you know the more complex and beautiful your website can be. This tutorial borrows heavily from a lot of great tutorials and resources you should check out too -- there are links throughout. 

The best way to learn is to follow along with your own laptop, but all are welcome. We'll spend half the time with the tutorial and half the time for you to work on your own website and get help. If you bring your laptop please do this beforehand: 

1. install [RStudio](https://www.rstudio.com/products/rstudio/download/)
1. create a [GitHub]((http://github.com)) account ([advice](http://happygitwithr.com/github-acct.html))
1. set up your computer to talk to GitHub
    - have RStudio linked directly (preferred) ([instructions sections 8-14](http://happygitwithr.com/hello-git.html))
    - or install the [Desktop App](https://desktop.github.com/)
    - or be familiar with git commands for the command line ([tutorial](https://try.github.io/levels/1/challenges/1))

----


**Examples:**

We have been using R Markdown for the Ocean Health Index:  [**ohi-science.org/ohi-global**](http://ohi-science.org/ohi-global).  
And R Markdown is much more than just websites -- here's a [**one-minute video about R Markdown**](http://rmarkdown.rstudio.com/lesson-1.html) to get you excited. 
